SecureAuthCorp/Configurations

- Templates/Applications/GenericWsFed.json
- Templates/Applications/Office365.json
- Templates/Applications/SAMLApplication.json
- Templates/Applications/Salesforce.json
- SAML Application template added
- updates to other templates for renderer
> SAML Application

- Templates/Applications/SAMLApplication.json
Add details page to template
rearrenge json to accept another view
> Application details

- Templates/Applications/SAMLApplication.json
- some fixes for saml attribute cards
> SAML App Template

- Templates/Applications/SAMLApplication.json
- json format fix
- large window for cert selection
> SAMLApp Bugs

- Templates/Applications/Salesforce.json
Details.
ProvidersInfo
Summary.
Update default view.
> New Salesforce templeate

- Templates/Applications/SAMLApplication.json
Add emptyValue for name
Add validation for groups and data stores
> Validations

- Templates/Applications/SAMLApplication.json
- Templates/Applications/Salesforce.json
- certificate selection empty states
- added cert selection to Salesforce
> SAML & Salesforce

- Templates/Applications/SAMLApplication.json
remove sourcer
get them from the dataModel
> Update login/logut url

- Templates/Applications/Salesforce.json
remove sourcer
get them from the dataModel
> update login/logout urls

- Templates/Applications/GenericWsFed.json
add templateName to avoid errors on sparkles
> Add templateName

- Templates/Applications/Salesforce.json
> Missing initiationTypeInfo

- Templates/Applications/SAMLApplication.json
Fix IDP-4560, now clicking in the text redirects to the page too.
> Service provider callout

- Templates/Applications/SAMLApplication.json
- Templates/Applications/Salesforce.json
- groups can now be separated with enter or a double space
> Application Groups

- Templates/Applications/Salesforce.json
Now the input is assertionConsumerService and replicates to spLoginUrl and recipient
> Change spLoginUrl for assertionConsumerService

- Templates/Applications/Concur.json
> v1 concur idp init

- Templates/Applications/Concur.json
> changed title, added id

- Templates/Applications/SAMLApplication.json
- Templates/Applications/Salesforce.json
Add notify when both values are 0.
Add modify when both values are 0.
Add empty values.
> Update behavior for assertion hours and minutes

- Templates/Applications/SAMLApplication.json
- Templates/Applications/Salesforce.json
This add the correct font to the text.
> Wrap color inside paragraph.

- Templates/Applications/Office365.json
Remove SAML template wording and change it for WS-Fed.
Add config panel
> Template updates

- Templates/Applications/Absolute.json
SP initiated (Redirect) template for Absolute
> Create Absolute.json file

- Templates/Applications/Accellion.json
SAML SP Initiated (Redirect) for Accellion
> Create Accellion.json file

- Templates/Applications/Office365.json
Add preview on Providers page and copy to clipboard funcionality, they are both the same text.
The code is replicated now cause I couldn't figure out using a variable for the script, there is probably a little work to be made in the renderer to make it fully functional.
Only one difference between the code for the Callout and the code for the copytoclipboard: For the callout the line breaks are ´</br>´ and for the copytoclipboard the linebreaks are `\n`
> Add PowerShellScript

- Templates/Applications/Office365.json
realmInfo is a statick, i need to use the realmNumber
> Fix the IDP Realm variable

- Templates/Applications/Office365.json
Add disclaimer and update the script with 'https:// 'in fron of host
> Update to Script

- Templates/Applications/Office365.json
whoever approve this can merge it pls? :D
> Change qaportal to comapanyname

- Templates/Applications/Office365.json
Revert to previous versions after Tuesday's demo.
> Changes for Demo

- Templates/Applications/Office365.json
This reverts commit 8cfdcb7741b5c8ecefd67b780b832eaa0f4490d2.
> Revert "Changes for Demo"

- Templates/Applications/Office365.json
This reverts commit 1a18922031e5084bfa55237992135f108992c60c.
> Revert "Demo pt. 2"

- Templates/Applications/GenericWsFed.json
- Templates/Applications/SAMLApplication.json
- Certificate is always required.
- Certificate selection section is always visible.
- Removed notifiers and modifiers from Assertion and Messages swtiches.
> Rework certificate section.

- Templates/Applications/Peakon.json
2 commas were missing under spLoginUrl field, added the same.
Committing in the branch fix-Peakon now.
> corrected-fix-Peakon

- Templates/Applications/Boxcryptor.json
Submitting new template Boxcryptor.json without the "devOnly" flag.
> Boxcryptor.json

- Templates/Applications/Brandfolder.json
Submitting without "devOnly" flag, new template Brandfolder.json. Please check this @Captison
> Brandfolder.json

- Templates/Applications/Bersin.json
Submitting new Bersin.json template without the "devOnly" flag.
Please validate @Captison
> Bersin.json

- Templates/Applications/Cherwell.json
Created Cherwell.json. Please validate this @Captison , I have submitted this new template without the "devOnly" flag.
> Cherwell.json

- Templates/Applications/Chromeriver.json
Submitting without devOnly flag, please validate Chromeriver.json template @Captison
> Chromeriver.json

- Templates/Applications/Contractworks.json
Contractworks.json, submitting the template without "devOnly" flag.
> Contractworks.json

- Templates/Applications/CaprizaPlatform.json
Submitting this new template CaprizaPlatform.json, without the "devOnly" flag.
> CaprizaPlatform.json

- Templates/Applications/Direct.json
Please validate the update-Direct commit for this new template Direct.json @Captison
> Direct.json

- Templates/Applications/Dmarcian.json
Submitting new template, without "devOnly" flag. Please approve.
> Dmarcian.json

- Templates/Applications/CompetencyIQ.json
Submitting new template, without "devOnly" flag, please validate.
> CompetencyIQ.json

- Templates/Applications/CAPPM.json
> CAPPM.json

- Templates/Applications/Pantheon.json
Please check the commit, Update-Pantheon.
> Pantheon.json

- Templates/Applications/oneteam.json
> oneteam.json

- Templates/Applications/skytap.json
> skytap.json

- Templates/Applications/CeridianDayforceHCM.json
> CeridianDayforceHCM.json

- Templates/Applications/CezanneHRSoftware.json
Submitting new template, without "devOnly" flag, please approve and merge.
> CezanneHRSoftware.json

- Templates/Applications/TableauServer.json
Submitting new template, without "devOnly" flag, please approve and merge.
> TableauServer.json

- Templates/Applications/YardieLearning.json
> YardieLearning.json

- Templates/Applications/IMAGEWORKS.json
> IMAGEWORKS.json

- Templates/Applications/LoginRadius.json
> LoginRadius.json

- Templates/Applications/Schoox.json
> Schoox.json

- Templates/Applications/Showpad.json
> Showpad.json

- Templates/Applications/ShucchoNavi.json
> ShucchoNavi.json

- Templates/Applications/Signagelive.json
> Signagelive.json

- Templates/Applications/Skilljar.json
> Skilljar.json

- Templates/Applications/Monday.com.json
> Monday.com.json

- Templates/Applications/RightAnswers.json
> RightAnswers.json

- Templates/Applications/HPESaaS.json
> HPESaaS.json

- Templates/Applications/InsiderTrack.json
> InsiderTrack.json

- Templates/Applications/EBSCO.json
> EBSCO.json

- Templates/Applications/EliOnboarding.json
> EliOnboarding.json

- Templates/Applications/Eluminate.json
> Eluminate.json

- Templates/Applications/EmpCenter.json
> EmpCenter.json

- Templates/Applications/Evidence.com.json
> Evidence.com.json

- Templates/Applications/BCintheCloud.json
> BCintheCloud.json

- Templates/Applications/ARESforEnterprise.json
> ARESforEnterprise.json

- Templates/Applications/AttendanceManagementServices.json
> AttendanceManagementServices.json

- Templates/Applications/RightScale.json
> Update and rename Rightscale.json to RightScale.json

- Templates/Applications/RingCentral.json
> Update and rename Ringcentral.json to RingCentral.json

- Templates/Applications/SilkRoadLifeSuite.json
> Update and rename silkroad_lifesuite.json to SilkRoadLifeSuite.json

- Templates/Applications/Statuspage.json
> Update and rename StatusPage.json to Statuspage.json

- Templates/Applications/Workpath.json
> Update and rename workpath.json to Workpath.json

- Templates/Applications/AppNeta.json
> Update and rename Appneta.json to AppNeta.json

- Templates/Applications/Pegasysems.json
> Update and rename pegasysems.json to Pegasysems.json

- Templates/Applications/monday.com.json
> Update and rename Monday.com.json to monday.com.json

- Templates/Applications/moconavi.json
> Update and rename Moconavi.json to moconavi.json

- Templates/Applications/MOBI.json
> Update and rename Mobi.json to MOBI.json

- Templates/Applications/Deem.json
> Update and rename DEEM.json to Deem.json

- Templates/Applications/CylancePROTECT.json
> Update and rename Cylance_Protect.json to CylancePROTECT.json

- Templates/Applications/CiscoWebex.json
Updated names; still in dev mode
> Update and rename webex.json to CiscoWebex.json
